USE delivery_DB;

INSERT INTO roles(role) VALUES ('admin')
INSERT INTO roles(role) VALUES ('customer')

INSERT INTO users(firstname,lastname,password,mail,phone,role_id) VALUES('Andrew','Mals','252525','abs@gmail.com','295676767',1)
INSERT INTO users(firstname,lastname,password,mail,phone,role_id) VALUES('Anton','Volegov','ant123','anton@mail.ru','297354939',2)
INSERT INTO users(firstname,lastname,password,mail,phone,role_id) VALUES('Alex','Makov','calc5467','calw@mail.ru','296579856',2)
INSERT INTO users(firstname,lastname,password,mail,phone,role_id) VALUES('Vasiliy','Kononov','qwerty12345','qwerty@gmail.com','442672474',1)
INSERT INTO users(firstname,lastname,password,mail,phone,role_id) VALUES('Denis','Andreev','awdrgty','denz21@mail.ru','295672327',2)
INSERT INTO users(firstname,lastname,password,mail,phone,role_id) VALUES('Andrew','Sergeev','wweeerrr','nevgiv@mail.ru','444448899',2)

INSERT INTO logs(user_id,message) VALUES(2,'Made a comment')
INSERT INTO logs(user_id,message) VALUES(3,'Applied promocode')
INSERT INTO logs(user_id,message) VALUES(5,'Made an order')
INSERT INTO logs(user_id,message) VALUES(2,'Made an order')
INSERT INTO logs(user_id,message) VALUES(5,'Applied promocode')
INSERT INTO logs(user_id,message) VALUES(1,'Anwered the comment')
INSERT INTO logs(user_id,message) VALUES(4,'Deleted meal')

INSERT INTO adress(city,street,building,entrance,floor,flat,user_id) VALUES('Minsk','Efrosinii Polockoi',12,2,3,23,1)
INSERT INTO adress(city,street,building,entrance,floor,flat,user_id) VALUES('Minsk','Melnikayte',54,3,6,125,2)
INSERT INTO adress(city,street,building,entrance,floor,flat,user_id) VALUES('Gomel','Kalugina',11,1,4,33,3)
INSERT INTO adress(city,street,building,entrance,floor,flat,user_id) VALUES('Grodno','Pobeditelei',1,3,3,53,4)
INSERT INTO adress(city,street,building,entrance,floor,flat,user_id) VALUES('Gomel','Efrosinii Polockoi',11,3,6,124,5)

INSERT INTO orders(creation_date,created_at,desired_at,comment,total_price,total_discount,user_id) VALUES(2022-11-11,10:22,11:00,'Was waiting too long. Awful delivery.',31.99,0,2)
INSERT INTO orders(creation_date,desired_at,comment,total_price,total_discount,user_id) VALUES(2022-11-16,16:00,16:30,'Tasty food.',21.99,10.0,3)
INSERT INTO orders(creation_date,desired_at,comment,total_price,total_discount,user_id) VALUES(2022-11-19,3:16,3:46,'Same as it was last time.Everything was good. Would advice you to order something.',53.98,10.0,3)
INSERT INTO orders(creation_date,desired_at,comment,total_price,total_discount,user_id) VALUES(2022-12-1,1:12,1:42,'Not bad, but i dont think ill use it again.',53.98,0,5)
INSERT INTO orders(creation_date,desired_at,comment,total_price,total_discount,user_id) VALUES(2022-12-2,21:22,22:00,'',41.99,21.99,3)

INSERT INTO promocodes(code,discount,description,valid_from,valid_until) VALUES('QWER-ASWQ-ASDA',10.0,'Have a good november with us',2022-11-1,2022-11-30)
INSERT INTO promocodes(code,discount,description,valid_from,valid_until) VALUES('SADF-GHJKJ-DASA',21.99,'Only tree days you can have a huge discount. Hurry up.',2022-12-1,2022-12-3)
INSERT INTO promocodes(code,discount,description,valid_from,valid_until) VALUES('LKJK-HXZG-OUDD',30.99,'Your chance to get food for free. Have fun.',2022-12-7,2022-12-8)

INSERT INTO applied_promocodes(order_id,promocode_id) VALUES(2,1)
INSERT INTO applied_promocodes(order_id,promocode_id) VALUES(3,1)
INSERT INTO applied_promocodes(order_id,promocode_id) VALUES(5,2)

INSERT INTO baskets(quantity,user_id) VALUES(2,2)
INSERT INTO baskets(quantity,user_id) VALUES(0,3)
INSERT INTO baskets(quantity,user_id) VALUES(3,5)

INSERT INTO meals(name,description,ingredients,weight,price) VALUES('4 seasons','4 diff sides','Ranch sauce, mushrooms, tomatoes, pepperoni, feta, pineapple, mozzarella cheese, shrimps',800,31.99)
INSERT INTO meals(name,description,ingredients,weight,price) VALUES('Munich','Like from there','Bavarian sausages, barbecue sauce, tomatoes, mustard, mozzarella cheese, Munich sausages, ham',900,21.99)
INSERT INTO meals(name,description,ingredients,weight,price) VALUES('Beef BBQ','Tho one with meat','Spinach, Bavarian sausages, mozzarella cheese, veal, cherry tomatoes, barbecue sauce',700,24.99)
INSERT INTO meals(name,description,ingredients,weight,price) VALUES('Chiken ranch','For them who prefers chiken','Ranch sauce, tomatoes, mozzarella cheese, chicken',650,20)
INSERT INTO meals(name,description,ingredients,weight,price) VALUES('Margarita','Classic','tomato sauce, mozzarella cheese',670,10)
INSERT INTO meals(name,description,ingredients,weight,price) VALUES('Cheddaroni','Experimentally','cream fresh, pepperoni, cheddar, ham, mozzarella cheese',1000,43.99)
INSERT INTO meals(name,description,ingredients,weight,price) VALUES('Carbonara','For those who love Italy','bacon, onion, mushrooms, ham, mozzarella cheese, fresh cream',450,8.50)
INSERT INTO meals(name,description,ingredients,weight,price) VALUES('Spicy','The name speaks itself','Pepperoni, jalapeno, mozzarella cheese, tomato sauce, bacon, tomatoes',550,14.50)

INSERT INTO basket_meal(basket_id,meal_id) VALUES(1,2)
INSERT INTO basket_meal(basket_id,meal_id) VALUES(1,2)
INSERT INTO basket_meal(basket_id,meal_id) VALUES(3,1)
INSERT INTO basket_meal(basket_id,meal_id) VALUES(3,4)
INSERT INTO basket_meal(basket_id,meal_id) VALUES(3,5)

INSERT INTO order_meal(order_id,meal_id) VALUES(1,1)
INSERT INTO order_meal(order_id,meal_id) VALUES(2,2)
INSERT INTO order_meal(order_id,meal_id) VALUES(3,1)
INSERT INTO order_meal(order_id,meal_id) VALUES(3,3)
INSERT INTO order_meal(order_id,meal_id) VALUES(4,2)
INSERT INTO order_meal(order_id,meal_id) VALUES(4,3)
INSERT INTO order_meal(order_id,meal_id) VALUES(4,5)
INSERT INTO order_meal(order_id,meal_id) VALUES(5,2)
INSERT INTO order_meal(order_id,meal_id) VALUES(5,4)

INSERT INTO meal_images(meal_id,url) VALUES(1,'https:///img/gallery/4seas.jpeg')
INSERT INTO meal_images(meal_id,url) VALUES(2,'https:///img/gallery/mun.png')
INSERT INTO meal_images(meal_id,url) VALUES(3,'https:///img/gallery/BBBQ.jpeg')
INSERT INTO meal_images(meal_id,url) VALUES(4,'https:///img/gallery/chiken.jpeg')
INSERT INTO meal_images(meal_id,url) VALUES(5,'https:///img/gallery/marg.jpeg')
INSERT INTO meal_images(meal_id,url) VALUES(6,'https:///img/gallery/ched.jpeg')
INSERT INTO meal_images(meal_id,url) VALUES(7,'https:///img/gallery/carb.jpeg')
INSERT INTO meal_images(meal_id,url) VALUES(8,'https:///img/gallery/spicy.jpeg')